name: Deploy Automático — EasyPanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger EasyPanel Deploy
        run: |
          curl -s -X GET "http://187.77.32.172:3000/api/deploy/bc1e226c81ecf965b309f70feb7260ab90e31168bfe1efa3"
          echo "Deploy triggerado com sucesso"
